package net.suncaper.projectprovider.mapper;

import java.util.List;
import net.suncaper.projectprovider.domain.JointCompany;
import net.suncaper.projectprovider.domain.JointCompanyExample;
import org.apache.ibatis.annotations.Param;

public interface JointCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_joint_company
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    long countByExample(JointCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_joint_company
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    int deleteByExample(JointCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_joint_company
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_joint_company
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    int insert(JointCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_joint_company
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    int insertSelective(JointCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_joint_company
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    List<JointCompany> selectByExample(JointCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_joint_company
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    JointCompany selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_joint_company
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    int updateByExampleSelective(@Param("record") JointCompany record, @Param("example") JointCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_joint_company
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    int updateByExample(@Param("record") JointCompany record, @Param("example") JointCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_joint_company
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    int updateByPrimaryKeySelective(JointCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_joint_company
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    int updateByPrimaryKey(JointCompany record);
}