package net.suncaper.projectprovider.mapper;

import java.util.List;
import net.suncaper.projectprovider.domain.ProjectLeaderExample;
import net.suncaper.projectprovider.domain.ProjectLeaderKey;
import org.apache.ibatis.annotations.Param;

public interface ProjectLeaderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_leader
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    long countByExample(ProjectLeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_leader
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    int deleteByExample(ProjectLeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_leader
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    int deleteByPrimaryKey(ProjectLeaderKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_leader
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    int insert(ProjectLeaderKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_leader
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    int insertSelective(ProjectLeaderKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_leader
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    List<ProjectLeaderKey> selectByExample(ProjectLeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_leader
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    int updateByExampleSelective(@Param("record") ProjectLeaderKey record, @Param("example") ProjectLeaderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_leader
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    int updateByExample(@Param("record") ProjectLeaderKey record, @Param("example") ProjectLeaderExample example);
}