package net.suncaper.projectprovider.mapper;

import java.util.List;
import net.suncaper.projectprovider.domain.ProjectJointCompanyExample;
import net.suncaper.projectprovider.domain.ProjectJointCompanyKey;
import org.apache.ibatis.annotations.Param;

public interface ProjectJointCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_project_joint_company
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    long countByExample(ProjectJointCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_project_joint_company
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    int deleteByExample(ProjectJointCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_project_joint_company
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    int deleteByPrimaryKey(ProjectJointCompanyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_project_joint_company
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    int insert(ProjectJointCompanyKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_project_joint_company
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    int insertSelective(ProjectJointCompanyKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_project_joint_company
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    List<ProjectJointCompanyKey> selectByExample(ProjectJointCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_project_joint_company
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    int updateByExampleSelective(@Param("record") ProjectJointCompanyKey record, @Param("example") ProjectJointCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_project_joint_company
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    int updateByExample(@Param("record") ProjectJointCompanyKey record, @Param("example") ProjectJointCompanyExample example);
}