package net.suncaper.projectprovider.mapper;

import java.util.List;
import net.suncaper.projectprovider.domain.ProjectDept;
import net.suncaper.projectprovider.domain.ProjectDeptExample;
import org.apache.ibatis.annotations.Param;

public interface ProjectDeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_project_dept
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    long countByExample(ProjectDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_project_dept
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    int deleteByExample(ProjectDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_project_dept
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_project_dept
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    int insert(ProjectDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_project_dept
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    int insertSelective(ProjectDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_project_dept
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    List<ProjectDept> selectByExample(ProjectDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_project_dept
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    ProjectDept selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_project_dept
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    int updateByExampleSelective(@Param("record") ProjectDept record, @Param("example") ProjectDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_project_dept
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    int updateByExample(@Param("record") ProjectDept record, @Param("example") ProjectDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_project_dept
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    int updateByPrimaryKeySelective(ProjectDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_project_dept
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    int updateByPrimaryKey(ProjectDept record);
}