package net.suncaper.projectprovider.mapper;

import java.util.List;
import net.suncaper.projectprovider.domain.ProjectImportanceExample;
import net.suncaper.projectprovider.domain.ProjectImportanceKey;
import org.apache.ibatis.annotations.Param;

public interface ProjectImportanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_project_importance
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    long countByExample(ProjectImportanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_project_importance
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    int deleteByExample(ProjectImportanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_project_importance
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    int deleteByPrimaryKey(ProjectImportanceKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_project_importance
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    int insert(ProjectImportanceKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_project_importance
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    int insertSelective(ProjectImportanceKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_project_importance
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    List<ProjectImportanceKey> selectByExample(ProjectImportanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_project_importance
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    int updateByExampleSelective(@Param("record") ProjectImportanceKey record, @Param("example") ProjectImportanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_project_importance
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    int updateByExample(@Param("record") ProjectImportanceKey record, @Param("example") ProjectImportanceExample example);
}