package net.suncaper.projectprovider.domain;

public class JointCompany {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_joint_company.id
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_joint_company.company_name
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_joint_company.compnay_id
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    private String compnayId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_joint_company.id
     *
     * @return the value of pt_joint_company.id
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_joint_company.id
     *
     * @param id the value for pt_joint_company.id
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_joint_company.company_name
     *
     * @return the value of pt_joint_company.company_name
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_joint_company.company_name
     *
     * @param companyName the value for pt_joint_company.company_name
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_joint_company.compnay_id
     *
     * @return the value of pt_joint_company.compnay_id
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    public String getCompnayId() {
        return compnayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_joint_company.compnay_id
     *
     * @param compnayId the value for pt_joint_company.compnay_id
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    public void setCompnayId(String compnayId) {
        this.compnayId = compnayId == null ? null : compnayId.trim();
    }
}