package net.suncaper.projectprovider.domain;

public class ProjectJointDeptKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_project_joint_dept.project_id
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_project_joint_dept.joint_dept_id
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    private Integer jointDeptId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_project_joint_dept.project_id
     *
     * @return the value of pt_project_joint_dept.project_id
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_project_joint_dept.project_id
     *
     * @param projectId the value for pt_project_joint_dept.project_id
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_project_joint_dept.joint_dept_id
     *
     * @return the value of pt_project_joint_dept.joint_dept_id
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    public Integer getJointDeptId() {
        return jointDeptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_project_joint_dept.joint_dept_id
     *
     * @param jointDeptId the value for pt_project_joint_dept.joint_dept_id
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    public void setJointDeptId(Integer jointDeptId) {
        this.jointDeptId = jointDeptId;
    }
}