package net.suncaper.projectprovider.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class ProjectExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pt_project
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pt_project
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pt_project
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_project
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    public ProjectExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_project
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_project
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_project
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_project
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_project
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_project
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_project
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_project
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_project
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_project
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pt_project
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andProjectTypeIdIsNull() {
            addCriterion("project_type_id is null");
            return (Criteria) this;
        }

        public Criteria andProjectTypeIdIsNotNull() {
            addCriterion("project_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjectTypeIdEqualTo(Integer value) {
            addCriterion("project_type_id =", value, "projectTypeId");
            return (Criteria) this;
        }

        public Criteria andProjectTypeIdNotEqualTo(Integer value) {
            addCriterion("project_type_id <>", value, "projectTypeId");
            return (Criteria) this;
        }

        public Criteria andProjectTypeIdGreaterThan(Integer value) {
            addCriterion("project_type_id >", value, "projectTypeId");
            return (Criteria) this;
        }

        public Criteria andProjectTypeIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("project_type_id >=", value, "projectTypeId");
            return (Criteria) this;
        }

        public Criteria andProjectTypeIdLessThan(Integer value) {
            addCriterion("project_type_id <", value, "projectTypeId");
            return (Criteria) this;
        }

        public Criteria andProjectTypeIdLessThanOrEqualTo(Integer value) {
            addCriterion("project_type_id <=", value, "projectTypeId");
            return (Criteria) this;
        }

        public Criteria andProjectTypeIdIn(List<Integer> values) {
            addCriterion("project_type_id in", values, "projectTypeId");
            return (Criteria) this;
        }

        public Criteria andProjectTypeIdNotIn(List<Integer> values) {
            addCriterion("project_type_id not in", values, "projectTypeId");
            return (Criteria) this;
        }

        public Criteria andProjectTypeIdBetween(Integer value1, Integer value2) {
            addCriterion("project_type_id between", value1, value2, "projectTypeId");
            return (Criteria) this;
        }

        public Criteria andProjectTypeIdNotBetween(Integer value1, Integer value2) {
            addCriterion("project_type_id not between", value1, value2, "projectTypeId");
            return (Criteria) this;
        }

        public Criteria andContactIdIsNull() {
            addCriterion("contact_id is null");
            return (Criteria) this;
        }

        public Criteria andContactIdIsNotNull() {
            addCriterion("contact_id is not null");
            return (Criteria) this;
        }

        public Criteria andContactIdEqualTo(Integer value) {
            addCriterion("contact_id =", value, "contactId");
            return (Criteria) this;
        }

        public Criteria andContactIdNotEqualTo(Integer value) {
            addCriterion("contact_id <>", value, "contactId");
            return (Criteria) this;
        }

        public Criteria andContactIdGreaterThan(Integer value) {
            addCriterion("contact_id >", value, "contactId");
            return (Criteria) this;
        }

        public Criteria andContactIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("contact_id >=", value, "contactId");
            return (Criteria) this;
        }

        public Criteria andContactIdLessThan(Integer value) {
            addCriterion("contact_id <", value, "contactId");
            return (Criteria) this;
        }

        public Criteria andContactIdLessThanOrEqualTo(Integer value) {
            addCriterion("contact_id <=", value, "contactId");
            return (Criteria) this;
        }

        public Criteria andContactIdIn(List<Integer> values) {
            addCriterion("contact_id in", values, "contactId");
            return (Criteria) this;
        }

        public Criteria andContactIdNotIn(List<Integer> values) {
            addCriterion("contact_id not in", values, "contactId");
            return (Criteria) this;
        }

        public Criteria andContactIdBetween(Integer value1, Integer value2) {
            addCriterion("contact_id between", value1, value2, "contactId");
            return (Criteria) this;
        }

        public Criteria andContactIdNotBetween(Integer value1, Integer value2) {
            addCriterion("contact_id not between", value1, value2, "contactId");
            return (Criteria) this;
        }

        public Criteria andSecretaryIdIsNull() {
            addCriterion("secretary_id is null");
            return (Criteria) this;
        }

        public Criteria andSecretaryIdIsNotNull() {
            addCriterion("secretary_id is not null");
            return (Criteria) this;
        }

        public Criteria andSecretaryIdEqualTo(Integer value) {
            addCriterion("secretary_id =", value, "secretaryId");
            return (Criteria) this;
        }

        public Criteria andSecretaryIdNotEqualTo(Integer value) {
            addCriterion("secretary_id <>", value, "secretaryId");
            return (Criteria) this;
        }

        public Criteria andSecretaryIdGreaterThan(Integer value) {
            addCriterion("secretary_id >", value, "secretaryId");
            return (Criteria) this;
        }

        public Criteria andSecretaryIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("secretary_id >=", value, "secretaryId");
            return (Criteria) this;
        }

        public Criteria andSecretaryIdLessThan(Integer value) {
            addCriterion("secretary_id <", value, "secretaryId");
            return (Criteria) this;
        }

        public Criteria andSecretaryIdLessThanOrEqualTo(Integer value) {
            addCriterion("secretary_id <=", value, "secretaryId");
            return (Criteria) this;
        }

        public Criteria andSecretaryIdIn(List<Integer> values) {
            addCriterion("secretary_id in", values, "secretaryId");
            return (Criteria) this;
        }

        public Criteria andSecretaryIdNotIn(List<Integer> values) {
            addCriterion("secretary_id not in", values, "secretaryId");
            return (Criteria) this;
        }

        public Criteria andSecretaryIdBetween(Integer value1, Integer value2) {
            addCriterion("secretary_id between", value1, value2, "secretaryId");
            return (Criteria) this;
        }

        public Criteria andSecretaryIdNotBetween(Integer value1, Integer value2) {
            addCriterion("secretary_id not between", value1, value2, "secretaryId");
            return (Criteria) this;
        }

        public Criteria andDeptIdIsNull() {
            addCriterion("dept_id is null");
            return (Criteria) this;
        }

        public Criteria andDeptIdIsNotNull() {
            addCriterion("dept_id is not null");
            return (Criteria) this;
        }

        public Criteria andDeptIdEqualTo(Integer value) {
            addCriterion("dept_id =", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotEqualTo(Integer value) {
            addCriterion("dept_id <>", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdGreaterThan(Integer value) {
            addCriterion("dept_id >", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("dept_id >=", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdLessThan(Integer value) {
            addCriterion("dept_id <", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdLessThanOrEqualTo(Integer value) {
            addCriterion("dept_id <=", value, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdIn(List<Integer> values) {
            addCriterion("dept_id in", values, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotIn(List<Integer> values) {
            addCriterion("dept_id not in", values, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdBetween(Integer value1, Integer value2) {
            addCriterion("dept_id between", value1, value2, "deptId");
            return (Criteria) this;
        }

        public Criteria andDeptIdNotBetween(Integer value1, Integer value2) {
            addCriterion("dept_id not between", value1, value2, "deptId");
            return (Criteria) this;
        }

        public Criteria andProjectStatusIdIsNull() {
            addCriterion("project_status_id is null");
            return (Criteria) this;
        }

        public Criteria andProjectStatusIdIsNotNull() {
            addCriterion("project_status_id is not null");
            return (Criteria) this;
        }

        public Criteria andProjectStatusIdEqualTo(Integer value) {
            addCriterion("project_status_id =", value, "projectStatusId");
            return (Criteria) this;
        }

        public Criteria andProjectStatusIdNotEqualTo(Integer value) {
            addCriterion("project_status_id <>", value, "projectStatusId");
            return (Criteria) this;
        }

        public Criteria andProjectStatusIdGreaterThan(Integer value) {
            addCriterion("project_status_id >", value, "projectStatusId");
            return (Criteria) this;
        }

        public Criteria andProjectStatusIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("project_status_id >=", value, "projectStatusId");
            return (Criteria) this;
        }

        public Criteria andProjectStatusIdLessThan(Integer value) {
            addCriterion("project_status_id <", value, "projectStatusId");
            return (Criteria) this;
        }

        public Criteria andProjectStatusIdLessThanOrEqualTo(Integer value) {
            addCriterion("project_status_id <=", value, "projectStatusId");
            return (Criteria) this;
        }

        public Criteria andProjectStatusIdIn(List<Integer> values) {
            addCriterion("project_status_id in", values, "projectStatusId");
            return (Criteria) this;
        }

        public Criteria andProjectStatusIdNotIn(List<Integer> values) {
            addCriterion("project_status_id not in", values, "projectStatusId");
            return (Criteria) this;
        }

        public Criteria andProjectStatusIdBetween(Integer value1, Integer value2) {
            addCriterion("project_status_id between", value1, value2, "projectStatusId");
            return (Criteria) this;
        }

        public Criteria andProjectStatusIdNotBetween(Integer value1, Integer value2) {
            addCriterion("project_status_id not between", value1, value2, "projectStatusId");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andTotalInvestmentIsNull() {
            addCriterion("total_investment is null");
            return (Criteria) this;
        }

        public Criteria andTotalInvestmentIsNotNull() {
            addCriterion("total_investment is not null");
            return (Criteria) this;
        }

        public Criteria andTotalInvestmentEqualTo(BigDecimal value) {
            addCriterion("total_investment =", value, "totalInvestment");
            return (Criteria) this;
        }

        public Criteria andTotalInvestmentNotEqualTo(BigDecimal value) {
            addCriterion("total_investment <>", value, "totalInvestment");
            return (Criteria) this;
        }

        public Criteria andTotalInvestmentGreaterThan(BigDecimal value) {
            addCriterion("total_investment >", value, "totalInvestment");
            return (Criteria) this;
        }

        public Criteria andTotalInvestmentGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("total_investment >=", value, "totalInvestment");
            return (Criteria) this;
        }

        public Criteria andTotalInvestmentLessThan(BigDecimal value) {
            addCriterion("total_investment <", value, "totalInvestment");
            return (Criteria) this;
        }

        public Criteria andTotalInvestmentLessThanOrEqualTo(BigDecimal value) {
            addCriterion("total_investment <=", value, "totalInvestment");
            return (Criteria) this;
        }

        public Criteria andTotalInvestmentIn(List<BigDecimal> values) {
            addCriterion("total_investment in", values, "totalInvestment");
            return (Criteria) this;
        }

        public Criteria andTotalInvestmentNotIn(List<BigDecimal> values) {
            addCriterion("total_investment not in", values, "totalInvestment");
            return (Criteria) this;
        }

        public Criteria andTotalInvestmentBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_investment between", value1, value2, "totalInvestment");
            return (Criteria) this;
        }

        public Criteria andTotalInvestmentNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_investment not between", value1, value2, "totalInvestment");
            return (Criteria) this;
        }

        public Criteria andYearInvestmentIsNull() {
            addCriterion("year_investment is null");
            return (Criteria) this;
        }

        public Criteria andYearInvestmentIsNotNull() {
            addCriterion("year_investment is not null");
            return (Criteria) this;
        }

        public Criteria andYearInvestmentEqualTo(BigDecimal value) {
            addCriterion("year_investment =", value, "yearInvestment");
            return (Criteria) this;
        }

        public Criteria andYearInvestmentNotEqualTo(BigDecimal value) {
            addCriterion("year_investment <>", value, "yearInvestment");
            return (Criteria) this;
        }

        public Criteria andYearInvestmentGreaterThan(BigDecimal value) {
            addCriterion("year_investment >", value, "yearInvestment");
            return (Criteria) this;
        }

        public Criteria andYearInvestmentGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("year_investment >=", value, "yearInvestment");
            return (Criteria) this;
        }

        public Criteria andYearInvestmentLessThan(BigDecimal value) {
            addCriterion("year_investment <", value, "yearInvestment");
            return (Criteria) this;
        }

        public Criteria andYearInvestmentLessThanOrEqualTo(BigDecimal value) {
            addCriterion("year_investment <=", value, "yearInvestment");
            return (Criteria) this;
        }

        public Criteria andYearInvestmentIn(List<BigDecimal> values) {
            addCriterion("year_investment in", values, "yearInvestment");
            return (Criteria) this;
        }

        public Criteria andYearInvestmentNotIn(List<BigDecimal> values) {
            addCriterion("year_investment not in", values, "yearInvestment");
            return (Criteria) this;
        }

        public Criteria andYearInvestmentBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("year_investment between", value1, value2, "yearInvestment");
            return (Criteria) this;
        }

        public Criteria andYearInvestmentNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("year_investment not between", value1, value2, "yearInvestment");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNull() {
            addCriterion("start_date is null");
            return (Criteria) this;
        }

        public Criteria andStartDateIsNotNull() {
            addCriterion("start_date is not null");
            return (Criteria) this;
        }

        public Criteria andStartDateEqualTo(String value) {
            addCriterion("start_date =", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotEqualTo(String value) {
            addCriterion("start_date <>", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThan(String value) {
            addCriterion("start_date >", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateGreaterThanOrEqualTo(String value) {
            addCriterion("start_date >=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThan(String value) {
            addCriterion("start_date <", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLessThanOrEqualTo(String value) {
            addCriterion("start_date <=", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateLike(String value) {
            addCriterion("start_date like", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotLike(String value) {
            addCriterion("start_date not like", value, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateIn(List<String> values) {
            addCriterion("start_date in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotIn(List<String> values) {
            addCriterion("start_date not in", values, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateBetween(String value1, String value2) {
            addCriterion("start_date between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andStartDateNotBetween(String value1, String value2) {
            addCriterion("start_date not between", value1, value2, "startDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNull() {
            addCriterion("end_date is null");
            return (Criteria) this;
        }

        public Criteria andEndDateIsNotNull() {
            addCriterion("end_date is not null");
            return (Criteria) this;
        }

        public Criteria andEndDateEqualTo(String value) {
            addCriterion("end_date =", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotEqualTo(String value) {
            addCriterion("end_date <>", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThan(String value) {
            addCriterion("end_date >", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateGreaterThanOrEqualTo(String value) {
            addCriterion("end_date >=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThan(String value) {
            addCriterion("end_date <", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLessThanOrEqualTo(String value) {
            addCriterion("end_date <=", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateLike(String value) {
            addCriterion("end_date like", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotLike(String value) {
            addCriterion("end_date not like", value, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateIn(List<String> values) {
            addCriterion("end_date in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotIn(List<String> values) {
            addCriterion("end_date not in", values, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateBetween(String value1, String value2) {
            addCriterion("end_date between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andEndDateNotBetween(String value1, String value2) {
            addCriterion("end_date not between", value1, value2, "endDate");
            return (Criteria) this;
        }

        public Criteria andYearIsNull() {
            addCriterion("year is null");
            return (Criteria) this;
        }

        public Criteria andYearIsNotNull() {
            addCriterion("year is not null");
            return (Criteria) this;
        }

        public Criteria andYearEqualTo(String value) {
            addCriterion("year =", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotEqualTo(String value) {
            addCriterion("year <>", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearGreaterThan(String value) {
            addCriterion("year >", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearGreaterThanOrEqualTo(String value) {
            addCriterion("year >=", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLessThan(String value) {
            addCriterion("year <", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLessThanOrEqualTo(String value) {
            addCriterion("year <=", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearLike(String value) {
            addCriterion("year like", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotLike(String value) {
            addCriterion("year not like", value, "year");
            return (Criteria) this;
        }

        public Criteria andYearIn(List<String> values) {
            addCriterion("year in", values, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotIn(List<String> values) {
            addCriterion("year not in", values, "year");
            return (Criteria) this;
        }

        public Criteria andYearBetween(String value1, String value2) {
            addCriterion("year between", value1, value2, "year");
            return (Criteria) this;
        }

        public Criteria andYearNotBetween(String value1, String value2) {
            addCriterion("year not between", value1, value2, "year");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNumIsNull() {
            addCriterion("company_id_num is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNumIsNotNull() {
            addCriterion("company_id_num is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNumEqualTo(String value) {
            addCriterion("company_id_num =", value, "companyIdNum");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNumNotEqualTo(String value) {
            addCriterion("company_id_num <>", value, "companyIdNum");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNumGreaterThan(String value) {
            addCriterion("company_id_num >", value, "companyIdNum");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNumGreaterThanOrEqualTo(String value) {
            addCriterion("company_id_num >=", value, "companyIdNum");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNumLessThan(String value) {
            addCriterion("company_id_num <", value, "companyIdNum");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNumLessThanOrEqualTo(String value) {
            addCriterion("company_id_num <=", value, "companyIdNum");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNumLike(String value) {
            addCriterion("company_id_num like", value, "companyIdNum");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNumNotLike(String value) {
            addCriterion("company_id_num not like", value, "companyIdNum");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNumIn(List<String> values) {
            addCriterion("company_id_num in", values, "companyIdNum");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNumNotIn(List<String> values) {
            addCriterion("company_id_num not in", values, "companyIdNum");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNumBetween(String value1, String value2) {
            addCriterion("company_id_num between", value1, value2, "companyIdNum");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNumNotBetween(String value1, String value2) {
            addCriterion("company_id_num not between", value1, value2, "companyIdNum");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pt_project
     *
     * @mbg.generated do_not_delete_during_merge Tue Dec 24 15:34:38 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table pt_project
     *
     * @mbg.generated Tue Dec 24 15:34:38 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}